apiVersion: v1
kind: Secret
metadata:
  name: awx-user-password
  namespace: crossplane-system
type: Opaque
stringData:
  password: myS3cur3P@ssw0rd
---
apiVersion: awxuser.crossplane.io/v1alpha1
kind: User
metadata:
  name: example-user
spec:
  forProvider:
    username: johndoe
    email: johndoe@example.com
    firstName: John
    lastName: Doe
    isSuperuser: false
    isSystemAuditor: false
    passwordSecretRef:
      name: awx-user-password
      namespace: crossplane-system
      key: password
  providerConfigRef:
    name: default
